---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: dhanush-webpage
          image: dhanushmahadevan/webapp:v1.8
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webpage
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
