- hosts: webservers
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Installing pre-requests tools to deploy a WordPress site
      apt:
        name: "{{item}}"
        state: present
      loop:
        - php
        - mysql
        - nginx
        
    - name: Start the Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
